// Code generated by "stringer -type=Index"; DO NOT EDIT.

package poc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
	_ = x[Juggler-14]
	_ = x[Fool-15]
}

const _Index_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKingJugglerFool"

var _Index_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52, 59, 63}

func (i Index) String() string {
	i -= 1
	if i >= Index(len(_Index_index)-1) {
		return "Index(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Index_name[_Index_index[i]:_Index_index[i+1]]
}
