// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package poc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hearts-1]
	_ = x[Clubs-2]
	_ = x[Diamonds-3]
	_ = x[Spades-4]
	_ = x[Joker-5]
}

const _Suit_name = "HeartsClubsDiamondsSpadesJoker"

var _Suit_index = [...]uint8{0, 6, 11, 19, 25, 30}

func (i Suit) String() string {
	i -= 1
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
