// Code generated by sqlc. DO NOT EDIT.

package sqlc

import ()

type Game struct {
	ID                  int64
	Score               int32
	MaxTimesThroughDeck int32
}

type History struct {
	ID         int64
	GameID     int64
	MoveID     int64
	MoveNumber int32
}

type Move struct {
	ID              int64
	OldPileNum      int16
	OldPileIndex    int16
	OldPilePosition int16
	NewPileNum      int16
	NewPileIndex    int16
	NewPilePosition int16
}

type PileCard struct {
	ID        int64
	PileNum   int16
	PileIndex int16
	Suit      int16
	Index     int16
	Position  int32
	GameID    int64
}
