// Code generated by sqlc. DO NOT EDIT.
// source: save_start_game.sql

package dbsqlc

import (
	"context"
)

const saveStartGame = `-- name: SaveStartGame :one

INSERT INTO game (score, max_times_through_deck)
VALUES ($1, $2)
RETURNING id, score, max_times_through_deck
`

type SaveStartGameParams struct {
	Score               int32
	MaxTimesThroughDeck int32
}

// Start a game.
func (q *Queries) SaveStartGame(ctx context.Context, arg SaveStartGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, saveStartGame, arg.Score, arg.MaxTimesThroughDeck)
	var i Game
	err := row.Scan(&i.ID, &i.Score, &i.MaxTimesThroughDeck)
	return i, err
}
