// Code generated by "stringer -type=Order"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[First-0]
	_ = x[Second-1]
	_ = x[Third-2]
}

const _Order_name = "FirstSecondThird"

var _Order_index = [...]uint8{0, 5, 11, 16}

func (i Order) String() string {
	if i < 0 || i >= Order(len(_Order_index)-1) {
		return "Order(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Order_name[_Order_index[i]:_Order_index[i+1]]
}
