// Code generated by "stringer -type=outputFormat"; DO NOT EDIT.

package stdlib

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Log-0]
	_ = x[JSON-1]
}

const _outputFormat_name = "LogJSON"

var _outputFormat_index = [...]uint8{0, 3, 7}

func (i outputFormat) String() string {
	if i >= outputFormat(len(_outputFormat_index)-1) {
		return "outputFormat(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _outputFormat_name[_outputFormat_index[i]:_outputFormat_index[i+1]]
}
